"""
G4Lite — Resupply Request Model
==================================

Full procurement workflow from initial request through approval,
ordering, delivery, and fulfillment. Designed to support both
requests for existing inventory items (restock) and requests for
entirely new items not yet in the catalogue.

Lifecycle:

    draft → pending → under_review → approved → ordered →
            partially_fulfilled → fulfilled
                                 → rejected
                                 → cancelled

Status transitions:
- draft → pending           : Requester submits
- pending → under_review    : Admin begins review
- under_review → approved   : Admin approves
- under_review → rejected   : Admin rejects (reason required)
- approved → ordered        : Admin places external order
- ordered → partially_fulfilled : Partial delivery received
- ordered → fulfilled       : Full delivery received
- any (except fulfilled) → cancelled : Requester or admin cancels

Design decisions:

REQUEST NUMBER
- `request_number` is a human-readable sequential ID formatted as
  "RSP-YYYYMM-NNNN" (e.g. RSP-202604-0012). Generated by the service
  layer, not auto-increment. This is what appears on printed demand
  forms and in email/radio references.

PRIORITY
- Four levels: routine, urgent, critical, emergency.
- `emergency` requests trigger critical notifications and skip
  the approval queue (flagged for immediate admin attention).

NEW ITEM REQUESTS
- When `item_id` is NULL, this is a request for an item not yet in
  inventory. The requester fills `item_name_freetext`, `item_description`,
  and optionally `suggested_category_id` + `suggested_supplier`.
- On fulfillment, the admin can create the new Item from the request.

COST TRACKING
- `estimated_unit_cost` and `quantity_requested` drive the cost estimate.
- `actual_unit_cost` and `quantity_fulfilled` track real spend.
- `budget_code` links to an external budget/cost centre.
- Costs are in the platform's base currency (GBP by default).

FULFILLMENT
- Partial fulfillment is supported: `quantity_fulfilled` can be less
  than `quantity_requested`, status becomes `partially_fulfilled`.
- `quantity_fulfilled` is updated incrementally as deliveries arrive.
- Full fulfillment triggers the item's available_quantity update.

DELIVERY TRACKING
- `supplier_name`, `supplier_reference`, `external_po_number` for
  linking to external procurement systems.
- `expected_delivery_date` and `actual_delivery_date` for tracking.

REJECTION
- `rejection_reason` is required when status moves to `rejected`.
- Separate from `admin_notes` which is ongoing commentary.
"""

from __future__ import annotations

import enum
from datetime import date, datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.database import Base

if TYPE_CHECKING:
    from app.models.category import Category
    from app.models.item import Item
    from app.models.user import User


# ── Enums ─────────────────────────────────────────────────────────


class ResupplyStatus(str, enum.Enum):
    """Lifecycle states for a resupply request."""

    draft = "draft"
    pending = "pending"
    under_review = "under_review"
    approved = "approved"
    rejected = "rejected"
    ordered = "ordered"
    partially_fulfilled = "partially_fulfilled"
    fulfilled = "fulfilled"
    cancelled = "cancelled"


class ResupplyPriority(str, enum.Enum):
    """Urgency level driving queue order and notification severity."""

    routine = "routine"
    urgent = "urgent"
    critical = "critical"
    emergency = "emergency"


# ── Valid status transitions (enforced by service layer) ──────────

RESUPPLY_STATUS_TRANSITIONS: dict[ResupplyStatus, set[ResupplyStatus]] = {
    ResupplyStatus.draft: {
        ResupplyStatus.pending,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.pending: {
        ResupplyStatus.under_review,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.under_review: {
        ResupplyStatus.approved,
        ResupplyStatus.rejected,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.approved: {
        ResupplyStatus.ordered,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.ordered: {
        ResupplyStatus.partially_fulfilled,
        ResupplyStatus.fulfilled,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.partially_fulfilled: {
        ResupplyStatus.fulfilled,
        ResupplyStatus.cancelled,
    },
    ResupplyStatus.rejected: set(),       # Terminal state
    ResupplyStatus.fulfilled: set(),      # Terminal state
    ResupplyStatus.cancelled: set(),      # Terminal state
}


# ── Model ─────────────────────────────────────────────────────────


class ResupplyRequest(Base):
    """Equipment resupply / procurement request with full lifecycle tracking."""

    __tablename__ = "resupply_requests"

    # ── Primary key ───────────────────────────────────────────────
    id: Mapped[int] = mapped_column(
        primary_key=True,
        index=True,
    )

    # ── Human-readable reference ──────────────────────────────────
    request_number: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        unique=True,
        index=True,
        comment="Sequential ref: RSP-YYYYMM-NNNN, generated by service layer",
    )

    # ── Existing item reference (restock) ─────────────────────────
    item_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("items.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        index=True,
        comment="FK to existing item. NULL = request for new item.",
    )

    # ── New item details (when item_id is NULL) ───────────────────
    item_name_freetext: Mapped[Optional[str]] = mapped_column(
        String(250),
        nullable=True,
        default=None,
        comment="Name of requested item when not in current inventory",
    )
    item_description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Description/specs for new item requests",
    )
    suggested_category_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("categories.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        comment="Suggested category for new item requests",
    )
    suggested_supplier: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        default=None,
        comment="Requester's suggested supplier or source",
    )

    # ── Request details ───────────────────────────────────────────
    quantity_requested: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Number of units requested",
    )
    justification: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Operational justification for the request",
    )
    priority: Mapped[ResupplyPriority] = mapped_column(
        Enum(ResupplyPriority, name="resupply_priority_enum"),
        nullable=False,
        default=ResupplyPriority.routine,
        comment="Urgency level: routine, urgent, critical, emergency",
    )
    required_by_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        default=None,
        comment="Date by which the items are operationally needed",
    )
    task_reference: Mapped[Optional[str]] = mapped_column(
        String(150),
        nullable=True,
        default=None,
        comment="Task, exercise, or project driving this request",
    )

    # ── Requester ─────────────────────────────────────────────────
    requested_by: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="User who submitted the request",
    )

    # ── Status workflow ───────────────────────────────────────────
    status: Mapped[ResupplyStatus] = mapped_column(
        Enum(ResupplyStatus, name="resupply_status_enum"),
        nullable=False,
        default=ResupplyStatus.pending,
        index=True,
        comment="Current lifecycle state",
    )

    # ── Review / approval ─────────────────────────────────────────
    reviewed_by: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        comment="Admin who reviewed the request",
    )
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of review start",
    )
    approved_by: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        comment="Admin who approved (may differ from reviewer)",
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of approval",
    )
    rejection_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Required explanation when request is rejected",
    )

    # ── Cost tracking ─────────────────────────────────────────────
    estimated_unit_cost: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        default=None,
        comment="Estimated cost per unit in base currency (GBP)",
    )
    actual_unit_cost: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        default=None,
        comment="Actual cost per unit after procurement",
    )
    budget_code: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        default=None,
        comment="External budget or cost centre reference",
    )

    # ── Fulfillment ───────────────────────────────────────────────
    quantity_fulfilled: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Units received so far (incremented on each delivery)",
    )
    fulfilled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when fully fulfilled",
    )
    fulfilled_by: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        comment="Admin who confirmed full fulfillment",
    )

    # ── External procurement ──────────────────────────────────────
    supplier_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        default=None,
        comment="Supplier or vendor name",
    )
    supplier_reference: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        default=None,
        comment="Supplier's order or quote reference",
    )
    external_po_number: Mapped[Optional[str]] = mapped_column(
        String(60),
        nullable=True,
        default=None,
        comment="External purchase order number",
    )

    # ── Delivery tracking ─────────────────────────────────────────
    expected_delivery_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        default=None,
        comment="Expected delivery from supplier",
    )
    actual_delivery_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        default=None,
        comment="Actual delivery date",
    )
    delivery_notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Notes on delivery (partial, damaged, etc.)",
    )

    # ── Admin commentary ──────────────────────────────────────────
    admin_notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Ongoing internal admin notes",
    )

    # ── Cancellation ──────────────────────────────────────────────
    cancelled_by: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        comment="User or admin who cancelled the request",
    )
    cancelled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of cancellation",
    )
    cancellation_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Reason for cancellation",
    )

    # ── Flags ─────────────────────────────────────────────────────
    is_new_item_request: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="True if requesting an item not in current inventory",
    )

    # ── Audit ─────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=True,
    )

    # ── Relationships ─────────────────────────────────────────────
    item: Mapped[Optional["Item"]] = relationship(
        "Item",
        back_populates="resupply_requests",
        lazy="joined",
    )
    suggested_category: Mapped[Optional["Category"]] = relationship(
        "Category",
        foreign_keys=[suggested_category_id],
        lazy="noload",
    )
    requester: Mapped["User"] = relationship(
        "User",
        foreign_keys=[requested_by],
        lazy="joined",
    )
    reviewer: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[reviewed_by],
        lazy="noload",
    )
    approver: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[approved_by],
        lazy="noload",
    )
    fulfiller: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[fulfilled_by],
        lazy="noload",
    )
    canceller: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[cancelled_by],
        lazy="noload",
    )

    # ── Table constraints ─────────────────────────────────────────
    __table_args__ = (
        # Quantity constraints
        CheckConstraint(
            "quantity_requested > 0",
            name="ck_resupply_qty_positive",
        ),
        CheckConstraint(
            "quantity_fulfilled >= 0",
            name="ck_resupply_fulfilled_positive",
        ),
        CheckConstraint(
            "quantity_fulfilled <= quantity_requested",
            name="ck_resupply_fulfilled_lte_requested",
        ),

        # Cost constraints
        CheckConstraint(
            "estimated_unit_cost IS NULL OR estimated_unit_cost >= 0",
            name="ck_resupply_est_cost_positive",
        ),
        CheckConstraint(
            "actual_unit_cost IS NULL OR actual_unit_cost >= 0",
            name="ck_resupply_actual_cost_positive",
        ),

        # Must have either item_id OR freetext name
        CheckConstraint(
            "item_id IS NOT NULL OR (item_name_freetext IS NOT NULL "
            "AND length(trim(item_name_freetext)) > 0)",
            name="ck_resupply_has_item_ref",
        ),

        # Rejection requires a reason
        CheckConstraint(
            "status != 'rejected' OR (rejection_reason IS NOT NULL "
            "AND length(trim(rejection_reason)) > 0)",
            name="ck_resupply_rejection_has_reason",
        ),

        # Cancellation requires a reason
        CheckConstraint(
            "status != 'cancelled' OR (cancellation_reason IS NOT NULL "
            "AND length(trim(cancellation_reason)) > 0)",
            name="ck_resupply_cancellation_has_reason",
        ),

        # Request number format
        CheckConstraint(
            "request_number ~ '^RSP-[0-9]{6}-[0-9]{4}$'",
            name="ck_resupply_request_number_format",
        ),

        # Query indexes
        Index("ix_resupply_status_priority", "status", "priority", "created_at"),
        Index("ix_resupply_requester_status", "requested_by", "status"),
        Index("ix_resupply_item_status", "item_id", "status"),
        Index("ix_resupply_required_by", "required_by_date"),
    )

    # ── Computed properties ───────────────────────────────────────
    @property
    def is_terminal(self) -> bool:
        """True if the request is in a final state."""
        return self.status in (
            ResupplyStatus.fulfilled,
            ResupplyStatus.rejected,
            ResupplyStatus.cancelled,
        )

    @property
    def is_active(self) -> bool:
        """True if the request is still in progress."""
        return not self.is_terminal

    @property
    def fulfillment_pct(self) -> float:
        """Percentage of requested quantity fulfilled. 0–100."""
        if self.quantity_requested == 0:
            return 0.0
        return round(
            (self.quantity_fulfilled / self.quantity_requested) * 100, 1
        )

    @property
    def quantity_outstanding(self) -> int:
        """Units still awaiting delivery."""
        return max(0, self.quantity_requested - self.quantity_fulfilled)

    @property
    def estimated_total_cost(self) -> float | None:
        """Estimated total cost based on unit estimate × quantity requested."""
        if self.estimated_unit_cost is None:
            return None
        return round(self.estimated_unit_cost * self.quantity_requested, 2)

    @property
    def actual_total_cost(self) -> float | None:
        """Actual total cost based on unit cost × quantity fulfilled."""
        if self.actual_unit_cost is None:
            return None
        return round(self.actual_unit_cost * self.quantity_fulfilled, 2)

    @property
    def display_item_name(self) -> str:
        """Return the item name whether this is an existing or new item request."""
        if self.item and self.item.name:
            return self.item.name
        return self.item_name_freetext or "Unknown Item"

    @property
    def is_overdue(self) -> bool:
        """True if past required_by_date and not yet fulfilled."""
        if self.required_by_date is None or self.is_terminal:
            return False
        return date.today() > self.required_by_date

    @property
    def days_until_required(self) -> int | None:
        """Days until the required_by_date. Negative = overdue."""
        if self.required_by_date is None:
            return None
        return (self.required_by_date - date.today()).days

    def can_transition_to(self, new_status: ResupplyStatus) -> tuple[bool, str]:
        """Check if a status transition is valid.

        Returns (allowed, reason) tuple.
        """
        valid_targets = RESUPPLY_STATUS_TRANSITIONS.get(self.status, set())
        if new_status in valid_targets:
            return True, "OK"
        return False, (
            f"Cannot transition from '{self.status.value}' to "
            f"'{new_status.value}'. Valid transitions: "
            f"{', '.join(s.value for s in valid_targets) or 'none (terminal state)'}"
        )

    def __repr__(self) -> str:
        return (
            f"<ResupplyRequest(id={self.id}, ref='{self.request_number}', "
            f"status='{self.status.value}', priority='{self.priority.value}', "
            f"qty={self.quantity_fulfilled}/{self.quantity_requested})>"
        )