"""initial schema

Revision ID: d5b90d4d3f29
Revises: 
Create Date: 2026-04-06 12:45:14.880346
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b90d4d3f29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Login username, lowercase alphanumeric + underscores'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address for account recovery and notifications'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash of current password'),
    sa.Column('last_password_hash', sa.String(length=255), nullable=True, comment='Previous password hash to prevent immediate reuse'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last password change'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='Force password change on next login (first login, admin reset)'),
    sa.Column('full_name', sa.String(length=120), nullable=False, comment='Display name used in UI, sign-out records, and reports'),
    sa.Column('rank', sa.String(length=50), nullable=True, comment='Military rank or organisational title'),
    sa.Column('service_number', sa.String(length=30), nullable=True, comment='Military or organisational service/staff number'),
    sa.Column('unit', sa.String(length=100), nullable=True, comment='Unit, team, squadron, or department'),
    sa.Column('contact_number', sa.String(length=30), nullable=True, comment='Phone number for overdue follow-up'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Relative path to profile image'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='IANA timezone for date/time display'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='Short bio or role description shown on profile'),
    sa.Column('role', sa.Enum('admin', 'user', 'viewer', name='user_role_enum'), nullable=False, comment='Platform access role: admin, user, viewer'),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts since last success'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp (null = not locked)'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent successful login'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='IP address of most recent login (IPv4 or IPv6)'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True, comment='Last API activity timestamp (throttled updates)'),
    sa.Column('login_count', sa.Integer(), nullable=False, comment='Total successful logins'),
    sa.Column('notify_in_app', sa.Boolean(), nullable=False, comment='Master toggle for in-app notifications'),
    sa.Column('notify_overdue', sa.Boolean(), nullable=False, comment='Receive overdue sign-out alerts'),
    sa.Column('notify_low_stock', sa.Boolean(), nullable=False, comment='Receive low-stock warnings'),
    sa.Column('notify_resupply', sa.Boolean(), nullable=False, comment='Receive resupply request notifications'),
    sa.Column('notify_signouts', sa.Boolean(), nullable=False, comment='Receive sign-out / return notifications'),
    sa.Column('notify_access', sa.Boolean(), nullable=False, comment='Receive access control notifications'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account enabled. Inactive accounts cannot authenticate.'),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of account deactivation'),
    sa.Column('deactivated_by', sa.Integer(), nullable=True, comment='Admin who deactivated this account'),
    sa.Column('deactivation_reason', sa.Text(), nullable=True, comment='Reason for account deactivation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Admin who created this account'),
    sa.CheckConstraint("email ~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'", name='ck_user_email_format'),
    sa.CheckConstraint("username ~ '^[a-z0-9_]{3,50}$'", name='ck_user_username_format'),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_user_failed_login_positive'),
    sa.CheckConstraint('is_active OR deactivated_at IS NOT NULL', name='ck_user_deactivation_has_timestamp'),
    sa.CheckConstraint('length(trim(full_name)) >= 2', name='ck_user_full_name_length'),
    sa.CheckConstraint('length(trim(timezone)) > 0', name='ck_user_timezone_not_empty'),
    sa.CheckConstraint('login_count >= 0', name='ck_user_login_count_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deactivated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_number')
    )
    op.create_index('ix_user_active_name', 'users', ['is_active', 'full_name'], unique=False)
    op.create_index('ix_user_last_active', 'users', ['last_active_at'], unique=False)
    op.create_index('ix_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False, comment='Human-readable category name'),
    sa.Column('slug', sa.String(length=140), nullable=False, comment='URL-safe identifier, auto-derived from name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Operational description of what this category covers'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='Short alpha code for labels and reports, e.g. COMP, COMMS, PWR'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent category ID. NULL = top-level category.'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order. Lower numbers first, ties broken by name.'),
    sa.Column('icon', sa.String(length=60), nullable=True, comment="MUI icon identifier, e.g. 'memory', 'router', 'bolt'"),
    sa.Column('colour', sa.String(length=7), nullable=True, comment="Hex colour for visual coding, e.g. '#3B82F6'. Null = theme accent."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete flag. Inactive categories hidden from selection UIs.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Admin who created this category'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='Admin who last modified this category'),
    sa.CheckConstraint("code IS NULL OR code ~ '^[A-Z0-9]{2,10}$'", name='ck_category_code_format'),
    sa.CheckConstraint("colour IS NULL OR colour ~ '^#[0-9A-Fa-f]{6}$'", name='ck_category_colour_hex'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id != id', name='ck_category_no_self_parent'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_category_parent_name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index('ix_category_active_sort', 'categories', ['is_active', 'sort_order', 'name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('signout', 'return_ok', 'return_damaged', 'return_condemned', 'overdue', 'low_stock', 'item_condition_change', 'resupply_request', 'resupply_status_change', 'access_granted', 'access_denied', 'access_pin_expired', 'user_account', 'system_alert', name='notification_type_enum'), nullable=False, comment='Event type that triggered this notification'),
    sa.Column('category', sa.Enum('inventory', 'resupply', 'access', 'admin', name='notification_category_enum'), nullable=False, comment='Grouping for frontend filter tabs'),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'critical', name='notification_priority_enum'), nullable=False, comment='Severity: low, normal, high, critical'),
    sa.Column('title', sa.String(length=250), nullable=False, comment="Short headline, e.g. 'Equipment signed out'"),
    sa.Column('body', sa.Text(), nullable=False, comment='Detailed message body'),
    sa.Column('icon', sa.String(length=60), nullable=True, comment='MUI icon identifier override. Null = auto from type.'),
    sa.Column('recipient_role', sa.String(length=20), nullable=False, comment="Target role: 'admin', 'user', or 'all'"),
    sa.Column('recipient_id', sa.Integer(), nullable=True, comment='Specific user target. NULL = role-wide broadcast.'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='PK of the related entity (item, signout, resupply, user, etc.)'),
    sa.Column('related_type', sa.String(length=50), nullable=True, comment="Entity type: 'item', 'signout', 'resupply', 'user', 'access_log'"),
    sa.Column('action_url', sa.String(length=300), nullable=True, comment="Relative URL for click-through, e.g. '/inventory/42'"),
    sa.Column('action_label', sa.String(length=60), nullable=True, comment="Button text, e.g. 'View Item', 'Review Request'"),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='User has seen this notification'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when marked as read'),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False, comment='Explicit confirmation for critical notifications'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when explicitly acknowledged'),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True, comment='User who acknowledged (may differ from recipient for admin actions)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Auto-hide after this time. NULL = never expires.'),
    sa.Column('source_service', sa.String(length=80), nullable=True, comment="Backend service that generated this, e.g. 'signout_service'"),
    sa.Column('triggered_by', sa.Integer(), nullable=True, comment='User whose action triggered this notification'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recipient_role IN ('admin', 'user', 'all')", name='ck_notification_recipient_role'),
    sa.CheckConstraint("related_type IS NULL OR related_type IN ('item', 'signout', 'resupply', 'user', 'access_log', 'category')", name='ck_notification_related_type'),
    sa.CheckConstraint('NOT is_acknowledged OR acknowledged_at IS NOT NULL', name='ck_notification_ack_has_timestamp'),
    sa.CheckConstraint('NOT is_read OR read_at IS NOT NULL', name='ck_notification_read_has_timestamp'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_category_created', 'notifications', ['category', 'created_at'], unique=False)
    op.create_index('ix_notification_critical_unacked', 'notifications', ['priority', 'is_acknowledged', 'created_at'], unique=False)
    op.create_index('ix_notification_expires', 'notifications', ['expires_at'], unique=False)
    op.create_index('ix_notification_recipient_unread', 'notifications', ['recipient_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_notification_role_unread', 'notifications', ['recipient_role', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Full display name, e.g. 'Raspberry Pi 4 Model B (8GB)'"),
    sa.Column('slug', sa.String(length=220), nullable=False, comment='URL-safe identifier, auto-derived from name'),
    sa.Column('item_code', sa.String(length=20), nullable=False, comment="Human-facing short code for labels and reports, e.g. 'RPI4-8GB'"),
    sa.Column('nsn', sa.String(length=16), nullable=True, comment="NATO Stock Number if applicable, e.g. '7025-99-123-4567'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed operational description and specifications'),
    sa.Column('short_description', sa.String(length=300), nullable=True, comment='One-line summary for card views and table rows'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='FK to categories. RESTRICT prevents deleting categories with items.'),
    sa.Column('manufacturer', sa.String(length=120), nullable=True, comment='Manufacturer or brand name'),
    sa.Column('model_number', sa.String(length=100), nullable=True, comment='Manufacturer model or part number'),
    sa.Column('total_quantity', sa.Integer(), nullable=False, comment='Total items on charge (all conditions + checked out)'),
    sa.Column('available_quantity', sa.Integer(), nullable=False, comment='Serviceable items not currently checked out'),
    sa.Column('serviceable_count', sa.Integer(), nullable=False, comment='Items in serviceable condition (on shelf)'),
    sa.Column('unserviceable_count', sa.Integer(), nullable=False, comment='Items requiring repair'),
    sa.Column('damaged_count', sa.Integer(), nullable=False, comment='Items damaged, awaiting assessment'),
    sa.Column('condemned_count', sa.Integer(), nullable=False, comment='Items beyond economical repair, awaiting disposal'),
    sa.Column('checked_out_count', sa.Integer(), nullable=False, comment='Items currently signed out (denormalized for fast queries)'),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False, comment='Low-stock warning threshold on available_quantity'),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False, comment='Suggested quantity for resupply requests'),
    sa.Column('unit_of_issue', sa.String(length=30), nullable=False, comment="Unit type: 'each', 'pack', 'metre', 'box', 'set', etc."),
    sa.Column('max_signout_quantity', sa.Integer(), nullable=False, comment='Max items a single user can sign out at once. 0 = no limit.'),
    sa.Column('storage_location', sa.String(length=60), nullable=True, comment="Primary location identifier, e.g. 'CAGE-A'"),
    sa.Column('shelf', sa.String(length=30), nullable=True, comment="Shelf within location, e.g. 'SHELF-03'"),
    sa.Column('bin', sa.String(length=30), nullable=True, comment="Bin within shelf, e.g. 'BIN-12'"),
    sa.Column('weight_grams', sa.Float(), nullable=True, comment='Unit weight in grams for packing lists'),
    sa.Column('dimensions', sa.String(length=60), nullable=True, comment="L×W×H in mm, e.g. '88×58×19.5'"),
    sa.Column('criticality', sa.String(length=10), nullable=False, comment='low | medium | high | critical — drives alert severity'),
    sa.Column('is_consumable', sa.Boolean(), nullable=False, comment='Consumable items are not expected to return'),
    sa.Column('is_serialised', sa.Boolean(), nullable=False, comment='Serialised items may have individual serial number tracking'),
    sa.Column('is_hazmat', sa.Boolean(), nullable=False, comment='Requires special handling procedures'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='Sign-outs require admin approval before access PIN generated'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment="Comma-separated tags for flexible search, e.g. 'gpio,prototype,field-kit'"),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment="Relative path to item image, e.g. '/uploads/items/rpi4-8gb.jpg'"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal admin notes — not shown to standard users'),
    sa.Column('handling_instructions', sa.Text(), nullable=True, comment='Special handling or storage instructions shown during sign-out'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete. Inactive items hidden from browse but preserved in history.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of soft-deletion'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Admin who created this item'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='Admin who last modified this item'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='Admin who deactivated this item'),
    sa.CheckConstraint("criticality IN ('low', 'medium', 'high', 'critical')", name='ck_item_criticality_enum'),
    sa.CheckConstraint("item_code ~ '^[A-Z0-9][A-Z0-9\\-]{1,18}[A-Z0-9]$'", name='ck_item_code_format'),
    sa.CheckConstraint("nsn IS NULL OR nsn ~ '^[0-9]{4}-[0-9]{2}-[0-9]{3}-[0-9]{4}$'", name='ck_item_nsn_format'),
    sa.CheckConstraint("unit_of_issue IN ('each', 'pack', 'pair', 'set', 'metre', 'roll', 'box', 'kit', 'spool', 'sheet', 'litre')", name='ck_item_unit_of_issue_enum'),
    sa.CheckConstraint('available_quantity <= serviceable_count', name='ck_item_avail_lte_serviceable'),
    sa.CheckConstraint('available_quantity >= 0', name='ck_item_avail_qty_positive'),
    sa.CheckConstraint('checked_out_count >= 0', name='ck_item_co_count_positive'),
    sa.CheckConstraint('condemned_count >= 0', name='ck_item_cond_count_positive'),
    sa.CheckConstraint('damaged_count >= 0', name='ck_item_dmg_count_positive'),
    sa.CheckConstraint('max_signout_quantity >= 0', name='ck_item_max_so_qty_positive'),
    sa.CheckConstraint('minimum_stock_level >= 0', name='ck_item_min_stock_positive'),
    sa.CheckConstraint('reorder_quantity >= 0', name='ck_item_reorder_qty_positive'),
    sa.CheckConstraint('serviceable_count >= 0', name='ck_item_svc_count_positive'),
    sa.CheckConstraint('total_quantity = serviceable_count + unserviceable_count + damaged_count + condemned_count + checked_out_count', name='ck_item_quantity_invariant'),
    sa.CheckConstraint('total_quantity >= 0', name='ck_item_total_qty_positive'),
    sa.CheckConstraint('unserviceable_count >= 0', name='ck_item_unsvc_count_positive'),
    sa.CheckConstraint('weight_grams IS NULL OR weight_grams > 0', name='ck_item_weight_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nsn')
    )
    op.create_index('ix_item_active_name', 'items', ['is_active', 'name'], unique=False)
    op.create_index('ix_item_category_active', 'items', ['category_id', 'is_active'], unique=False)
    op.create_index('ix_item_criticality_active', 'items', ['criticality', 'is_active'], unique=False)
    op.create_index('ix_item_location', 'items', ['storage_location', 'shelf', 'bin'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=True)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_slug'), 'items', ['slug'], unique=True)
    op.create_table('resupply_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False, comment='Sequential ref: RSP-YYYYMM-NNNN, generated by service layer'),
    sa.Column('item_id', sa.Integer(), nullable=True, comment='FK to existing item. NULL = request for new item.'),
    sa.Column('item_name_freetext', sa.String(length=250), nullable=True, comment='Name of requested item when not in current inventory'),
    sa.Column('item_description', sa.Text(), nullable=True, comment='Description/specs for new item requests'),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True, comment='Suggested category for new item requests'),
    sa.Column('suggested_supplier', sa.String(length=200), nullable=True, comment="Requester's suggested supplier or source"),
    sa.Column('quantity_requested', sa.Integer(), nullable=False, comment='Number of units requested'),
    sa.Column('justification', sa.Text(), nullable=False, comment='Operational justification for the request'),
    sa.Column('priority', sa.Enum('routine', 'urgent', 'critical', 'emergency', name='resupply_priority_enum'), nullable=False, comment='Urgency level: routine, urgent, critical, emergency'),
    sa.Column('required_by_date', sa.Date(), nullable=True, comment='Date by which the items are operationally needed'),
    sa.Column('task_reference', sa.String(length=150), nullable=True, comment='Task, exercise, or project driving this request'),
    sa.Column('requested_by', sa.Integer(), nullable=False, comment='User who submitted the request'),
    sa.Column('status', sa.Enum('draft', 'pending', 'under_review', 'approved', 'rejected', 'ordered', 'partially_fulfilled', 'fulfilled', 'cancelled', name='resupply_status_enum'), nullable=False, comment='Current lifecycle state'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='Admin who reviewed the request'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of review start'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='Admin who approved (may differ from reviewer)'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of approval'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Required explanation when request is rejected'),
    sa.Column('estimated_unit_cost', sa.Float(), nullable=True, comment='Estimated cost per unit in base currency (GBP)'),
    sa.Column('actual_unit_cost', sa.Float(), nullable=True, comment='Actual cost per unit after procurement'),
    sa.Column('budget_code', sa.String(length=50), nullable=True, comment='External budget or cost centre reference'),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False, comment='Units received so far (incremented on each delivery)'),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when fully fulfilled'),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True, comment='Admin who confirmed full fulfillment'),
    sa.Column('supplier_name', sa.String(length=200), nullable=True, comment='Supplier or vendor name'),
    sa.Column('supplier_reference', sa.String(length=100), nullable=True, comment="Supplier's order or quote reference"),
    sa.Column('external_po_number', sa.String(length=60), nullable=True, comment='External purchase order number'),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True, comment='Expected delivery from supplier'),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True, comment='Actual delivery date'),
    sa.Column('delivery_notes', sa.Text(), nullable=True, comment='Notes on delivery (partial, damaged, etc.)'),
    sa.Column('admin_notes', sa.Text(), nullable=True, comment='Ongoing internal admin notes'),
    sa.Column('cancelled_by', sa.Integer(), nullable=True, comment='User or admin who cancelled the request'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of cancellation'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='Reason for cancellation'),
    sa.Column('is_new_item_request', sa.Boolean(), nullable=False, comment='True if requesting an item not in current inventory'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("request_number ~ '^RSP-[0-9]{6}-[0-9]{4}$'", name='ck_resupply_request_number_format'),
    sa.CheckConstraint("status != 'cancelled' OR (cancellation_reason IS NOT NULL AND length(trim(cancellation_reason)) > 0)", name='ck_resupply_cancellation_has_reason'),
    sa.CheckConstraint("status != 'rejected' OR (rejection_reason IS NOT NULL AND length(trim(rejection_reason)) > 0)", name='ck_resupply_rejection_has_reason'),
    sa.CheckConstraint('actual_unit_cost IS NULL OR actual_unit_cost >= 0', name='ck_resupply_actual_cost_positive'),
    sa.CheckConstraint('estimated_unit_cost IS NULL OR estimated_unit_cost >= 0', name='ck_resupply_est_cost_positive'),
    sa.CheckConstraint('item_id IS NOT NULL OR (item_name_freetext IS NOT NULL AND length(trim(item_name_freetext)) > 0)', name='ck_resupply_has_item_ref'),
    sa.CheckConstraint('quantity_fulfilled <= quantity_requested', name='ck_resupply_fulfilled_lte_requested'),
    sa.CheckConstraint('quantity_fulfilled >= 0', name='ck_resupply_fulfilled_positive'),
    sa.CheckConstraint('quantity_requested > 0', name='ck_resupply_qty_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resupply_item_status', 'resupply_requests', ['item_id', 'status'], unique=False)
    op.create_index('ix_resupply_requester_status', 'resupply_requests', ['requested_by', 'status'], unique=False)
    op.create_index(op.f('ix_resupply_requests_id'), 'resupply_requests', ['id'], unique=False)
    op.create_index(op.f('ix_resupply_requests_item_id'), 'resupply_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_resupply_requests_request_number'), 'resupply_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_resupply_requests_requested_by'), 'resupply_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_resupply_requests_status'), 'resupply_requests', ['status'], unique=False)
    op.create_index('ix_resupply_required_by', 'resupply_requests', ['required_by_date'], unique=False)
    op.create_index('ix_resupply_status_priority', 'resupply_requests', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('signouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signout_ref', sa.String(length=20), nullable=False, comment='Sequential ref: SO-YYYYMM-NNNN, generated by service layer'),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='FK to item being signed out. RESTRICT prevents deleting items with active sign-outs.'),
    sa.Column('item_code_snapshot', sa.String(length=20), nullable=True, comment='Item code at time of sign-out (denormalized for history/reports)'),
    sa.Column('item_name_snapshot', sa.String(length=200), nullable=True, comment='Item name at time of sign-out (denormalized for history/reports)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK to the platform user performing the sign-out'),
    sa.Column('full_name', sa.String(length=120), nullable=False, comment='Full name of person collecting equipment (may differ from user account)'),
    sa.Column('rank', sa.String(length=50), nullable=True, comment='Rank or title of the person collecting'),
    sa.Column('unit', sa.String(length=100), nullable=True, comment='Unit, team, or department'),
    sa.Column('contact_number', sa.String(length=30), nullable=True, comment='Contact number for follow-up on overdue items'),
    sa.Column('task_reference', sa.String(length=200), nullable=False, comment='Task, exercise, operation, or project reference'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='Detailed purpose or justification for the sign-out'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of units signed out'),
    sa.Column('quantity_returned', sa.Integer(), nullable=False, comment='Total units returned so far (sum of all conditions)'),
    sa.Column('quantity_returned_serviceable', sa.Integer(), nullable=False, comment='Units returned in serviceable condition'),
    sa.Column('quantity_returned_unserviceable', sa.Integer(), nullable=False, comment='Units returned in unserviceable condition'),
    sa.Column('quantity_returned_damaged', sa.Integer(), nullable=False, comment='Units returned in damaged condition'),
    sa.Column('quantity_returned_condemned', sa.Integer(), nullable=False, comment='Units returned condemned (beyond repair)'),
    sa.Column('expected_return_date', sa.Date(), nullable=False, comment='Current expected return date (may be extended)'),
    sa.Column('original_return_date', sa.Date(), nullable=False, comment='Original return date at time of sign-out (preserved through extensions)'),
    sa.Column('duration_days', sa.Integer(), nullable=True, comment='Planned duration in days (informational)'),
    sa.Column('extension_count', sa.Integer(), nullable=False, comment='Number of times the return date has been extended'),
    sa.Column('last_extended_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent extension'),
    sa.Column('last_extended_by', sa.Integer(), nullable=True, comment='Admin or user who last extended the return date'),
    sa.Column('condition_on_issue', sa.Enum('serviceable', 'unserviceable', 'damaged', 'condemned', name='equipment_condition_enum'), nullable=False, comment='Condition of equipment when issued (baseline for return comparison)'),
    sa.Column('condition_on_return', sa.Enum('serviceable', 'unserviceable', 'damaged', 'condemned', name='equipment_condition_enum'), nullable=True, comment='Overall condition on return (worst condition if mixed)'),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'active', 'partially_returned', 'overdue', 'returned', 'lost', name='signout_status_enum'), nullable=False, comment='Current lifecycle state'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Sign-out notes from the requester'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='Admin who approved the sign-out'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True, comment='Reason for rejection (required when status = rejected)'),
    sa.Column('signed_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when sign-out record was created'),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when equipment was physically collected (access PIN used)'),
    sa.Column('access_code_id', sa.Integer(), nullable=True, comment='FK to access_codes table (physical security integration)'),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of final return (all items accounted for)'),
    sa.Column('return_notes', sa.Text(), nullable=True, comment='Notes provided on return (user-facing)'),
    sa.Column('damage_description', sa.Text(), nullable=True, comment='Detailed damage report if items returned damaged/condemned'),
    sa.Column('received_by', sa.Integer(), nullable=True, comment='Admin who processed and verified the return'),
    sa.Column('return_inspected', sa.Boolean(), nullable=False, comment='True if condition was physically verified by admin, not self-reported'),
    sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True, comment='When the first overdue notification was sent'),
    sa.Column('overdue_escalated_at', sa.DateTime(timezone=True), nullable=True, comment='When the escalation notification was sent (e.g. 48h overdue)'),
    sa.Column('lost_declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_declared_by', sa.Integer(), nullable=True),
    sa.Column('loss_report', sa.Text(), nullable=True, comment='Narrative description of how/when equipment was lost'),
    sa.Column('quantity_lost', sa.Integer(), nullable=False, comment='Number of units declared lost'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("signout_ref ~ '^SO-[0-9]{6}-[0-9]{4}$'", name='ck_signout_ref_format'),
    sa.CheckConstraint("status != 'lost' OR (loss_report IS NOT NULL AND length(trim(loss_report)) > 0)", name='ck_signout_loss_has_report'),
    sa.CheckConstraint("status != 'rejected' OR (rejected_reason IS NOT NULL AND length(trim(rejected_reason)) > 0)", name='ck_signout_rejection_has_reason'),
    sa.CheckConstraint('duration_days IS NULL OR duration_days > 0', name='ck_signout_duration_positive'),
    sa.CheckConstraint('extension_count >= 0', name='ck_signout_extension_count_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_signout_qty_positive'),
    sa.CheckConstraint('quantity_lost >= 0', name='ck_signout_lost_positive'),
    sa.CheckConstraint('quantity_returned + quantity_lost <= quantity', name='ck_signout_return_plus_lost_lte_qty'),
    sa.CheckConstraint('quantity_returned = quantity_returned_serviceable + quantity_returned_unserviceable + quantity_returned_damaged + quantity_returned_condemned', name='ck_signout_return_breakdown_sum'),
    sa.CheckConstraint('quantity_returned >= 0', name='ck_signout_returned_positive'),
    sa.CheckConstraint('quantity_returned_condemned >= 0', name='ck_signout_ret_cond_positive'),
    sa.CheckConstraint('quantity_returned_damaged >= 0', name='ck_signout_ret_dmg_positive'),
    sa.CheckConstraint('quantity_returned_serviceable >= 0', name='ck_signout_ret_svc_positive'),
    sa.CheckConstraint('quantity_returned_unserviceable >= 0', name='ck_signout_ret_unsvc_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_extended_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lost_declared_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signout_active_items', 'signouts', ['item_id', 'status', 'quantity'], unique=False)
    op.create_index('ix_signout_item_status', 'signouts', ['item_id', 'status'], unique=False)
    op.create_index('ix_signout_overdue_check', 'signouts', ['status', 'expected_return_date', 'overdue_notified_at'], unique=False)
    op.create_index('ix_signout_status_date', 'signouts', ['status', 'expected_return_date'], unique=False)
    op.create_index('ix_signout_user_status', 'signouts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_signouts_id'), 'signouts', ['id'], unique=False)
    op.create_index(op.f('ix_signouts_item_id'), 'signouts', ['item_id'], unique=False)
    op.create_index(op.f('ix_signouts_signout_ref'), 'signouts', ['signout_ref'], unique=True)
    op.create_index(op.f('ix_signouts_status'), 'signouts', ['status'], unique=False)
    op.create_index(op.f('ix_signouts_user_id'), 'signouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signouts_user_id'), table_name='signouts')
    op.drop_index(op.f('ix_signouts_status'), table_name='signouts')
    op.drop_index(op.f('ix_signouts_signout_ref'), table_name='signouts')
    op.drop_index(op.f('ix_signouts_item_id'), table_name='signouts')
    op.drop_index(op.f('ix_signouts_id'), table_name='signouts')
    op.drop_index('ix_signout_user_status', table_name='signouts')
    op.drop_index('ix_signout_status_date', table_name='signouts')
    op.drop_index('ix_signout_overdue_check', table_name='signouts')
    op.drop_index('ix_signout_item_status', table_name='signouts')
    op.drop_index('ix_signout_active_items', table_name='signouts')
    op.drop_table('signouts')
    op.drop_index('ix_resupply_status_priority', table_name='resupply_requests')
    op.drop_index('ix_resupply_required_by', table_name='resupply_requests')
    op.drop_index(op.f('ix_resupply_requests_status'), table_name='resupply_requests')
    op.drop_index(op.f('ix_resupply_requests_requested_by'), table_name='resupply_requests')
    op.drop_index(op.f('ix_resupply_requests_request_number'), table_name='resupply_requests')
    op.drop_index(op.f('ix_resupply_requests_item_id'), table_name='resupply_requests')
    op.drop_index(op.f('ix_resupply_requests_id'), table_name='resupply_requests')
    op.drop_index('ix_resupply_requester_status', table_name='resupply_requests')
    op.drop_index('ix_resupply_item_status', table_name='resupply_requests')
    op.drop_table('resupply_requests')
    op.drop_index(op.f('ix_items_slug'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index('ix_item_location', table_name='items')
    op.drop_index('ix_item_criticality_active', table_name='items')
    op.drop_index('ix_item_category_active', table_name='items')
    op.drop_index('ix_item_active_name', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notification_role_unread', table_name='notifications')
    op.drop_index('ix_notification_recipient_unread', table_name='notifications')
    op.drop_index('ix_notification_expires', table_name='notifications')
    op.drop_index('ix_notification_critical_unacked', table_name='notifications')
    op.drop_index('ix_notification_category_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_category_active_sort', table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_role_active', table_name='users')
    op.drop_index('ix_user_last_active', table_name='users')
    op.drop_index('ix_user_active_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
